### PR TITLE
[actions][cwl-auto] use ubuntu 22.04

### PR DESCRIPTION
**Pull request by dglaeser**

### CODE REVIEW

**Comment by dglaeser** [comment]
@pdiercks, @onluen, it seems that this fixes the cwl-auto job, however, aiida failed here (although I didn't make any changes to it). Any ideas what that error means?

**Comment by dglaeser** [comment]
sorry, I looked at the wrong job. cwl-auto-conda actually hasn't started yet...

**Comment by pdiercks** [comment]
Thanks @dglaeser ,
the issue with the AiiDA action is probably that pip picks up the new version of `aiida-core`. I already opened an issue #63 for this.
I suggest that I submit an independent PR to fix the aiida action.

**Comment by pdiercks** [comment]
Hi @dglaeser ,

I would now merge this PR and also #65. (all checks pass again)

**Comment by dglaeser** [comment]
hi @pdiercks, thats what I meant in my other comment. We had issues like this before once... so maybe let us leave this PR open and unmerged for the moment... if it's possible, it's maybe nicer to use the same runner in all jobs.

**Comment by pdiercks** [comment]
Hi @dglaeser ,
I think we do not need to merge and close this?

**Comment by dglaeser** [comment]
@pdiercks, yes, I'll close it

**Pull request closed without merging**
