### PR TITLE
Feature/port cwl wf

### PR DESCRIPTION
**Pull request by dglaeser**
@pdiercks, this adapts the cwl workflow to your changes brough in with #33

### CODE REVIEW

**Comment by dglaeser** [comment]
I will close #34 in favor of this one (the name of #34 did not fit anymore). Note that in the first commit I made the num-dofs-output-file optional because e.g. for cwl I don't need it.

**Comment by dglaeser** [comment]
At least locally the CWL worflow works for me.

**Comment by pdiercks** [comment]
Thanks @dglaeser !
> At least locally the CWL worflow works for me.

So making use of conda for the enviroment would be the only missing change required?

**Comment by dglaeser** [comment]
> So making use of conda for the enviroment would be the only missing change required?
I don't think there is any change required, I actually used conda to set up the environment (as described in the README). I meant that I haven't (couldn't) check it in the pipelines, just tried it locally.

**Comment by pdiercks** [comment]
Nevermind, everything looks good. :)

**Pull request merged**
