### PR TITLE
Feature/simpleusecase cwl

### PR DESCRIPTION
**Pull request by dglaeser**

### CODE REVIEW

**Comment by pdiercks** [comment]
Hi @dglaeser ,
I have some minor comments/questions:
1. In the case of snakemake and pydoit I put the compute environment specification in the respective folder, i.e. the env spec is specific to the tool. Would you rather collect all environments in a top level environments folder?
2. Also related to point 1. installing paraview via conda and then removing it, it would be better to have a cwlenv.yaml where paraview is not listed
3. I guess it won't do a lot but cleaning up with `conda clean --all -y` would reduce the size of the docker image

**Comment by dglaeser** [comment]
thanks for your comments @pdiercks. Yes, I also thought about a separate environment file without ParaView, but then I was wondering if we maybe want to have one central place where define the environments/dependencies to make sure all tool implementations use the same (in case they support conda at least). Then we could change e.g. a version number in a central place and rerun the actions to see if all still works.

That is also why I put the environments in a separate folder, I forgot to mention this in the description. This is of course subject to discussion. I named the environment `complete` for now, thinking that we may want to have separate files for the individual steps, i.e. `preprocession.yml`, `postprocessing.yml`, etc... What do you think?

**Comment by pdiercks** [comment]
Hi @dglaeser , 
I like the idea of having a `complete.yaml` in one central place, but this is only useful if the different workflow implementation use this file and in the cwl case installing and re-installing paraview is certainly not the best and in the snakemake case it makes sense (it's easy) to just split the environments for the individual steps, but in case of pydoit this is not that easy to accomplish. So we might end up with an `env.yaml` (or something else if conda is not supported) for each tool and then we might as well just put it in the respective subfolder. 

Another idea could be that we define a `complete.yaml` and generate the `env.yaml` for each tool from this file, but this might complicate things ...

**Comment by dglaeser** [comment]
> Another idea could be that we define a complete.yaml and generate the env.yaml for each tool from this file, but this might complicate things ...

But so for any tool that allows conda integration, these files would look identical, right? That's why I thought a central place may make sense... If we find out the remaining tools we look at have no conda integration we can again kick that out, but then I would also do the container without conda... 

> and in the cwl case installing and re-installing paraview is certainly not the best 

It's not CWL that causes this particular problem, but it seems that for rendering operations standard paraviews needs an x-server connection which is problematic inside a container - that's why I am using the osmesa-build which is suitable for such situations. So the "problem" is containers in general. And installing, removing and re-installing ideally happens only once when we build the image, which we then provide somewhere... 

I am ok if we decide against this, just wanted to comment on these two points.

**Comment by pdiercks** [comment]
So, I am going to merge this for now, since I could also run it locally without error.

**Pull request merged**
