### PR TITLE
Feature/refactor postprocessing

### PR DESCRIPTION
**Pull request by pdiercks**
Hi @dglaeser, 
I changed the postprocessing step to PlotOverLine. The data is written to a CSV file which is read when plotting the data in the final paper. 
I adjusted the pydoit, snakemake, nextflow and cwl workflows, but did only test the pydoit WF.

### CODE REVIEW

**Comment by dglaeser** [comment]
Hi @pdiercks, thanks a lot. I will rebase the other branch and test CWL. If it works, I would merge this one, ok?

**Comment by dglaeser** [comment]
with my last fix CWL works, see #21. I would add the other tools into the actions pipeline and put that into a separate PR... Then, this implicitly tests all changes of this branch. If everything works I would merge this here, then #21, and then the actions branch. What do you think?

**Comment by pdiercks** [comment]
Agreed.

**Comment by dglaeser** [comment]
from my side we can merge this, any objections?

**Pull request merged**
