### PR TITLE
Simplify gwl workflow

### PR DESCRIPTION
**Pull request by onluen**
Rewrites the gwl workflow in more idiomatic wisp as mentioned in the gwl developer feedback. 

`paraview` and `cgns` packages have been upstreamed to guix. The custom container generated by support scripts in `build-aux` isn't required anymore and a guix github action is used instead.

### CODE REVIEW

**Comment by pdiercks** [comment]
Hi @onluen , thanks!
the changes wrt the gwl workflow look good to me. 
Any idea what happened to the `run-cwl-auto-conda` action (@dglaeser ) ?

**Comment by dglaeser** [comment]
hm, I think we had a very similar issue before some time. I was trying to find my comments or PRs from back then but I couldn't find it anymore. However, I seem to remember that it turned out to be an error on the cwltool side regarding package resolving, that was then fixed by them and the pipeline then worked again...

**Comment by dglaeser** [comment]
I'm trying that on #64, if it works we can maybe rebase this one here, try again, and merge if it works

**Comment by pdiercks** [comment]
Hi @onluen , 
could you please try to rebase on main and see if the actions pass?

**Comment by onluen** [comment]
@dglaeser seems to work now. Thanks!

**Comment by dglaeser** [comment]
Cool, @pdiercks we can merge this now, right?

**Pull request merged**
